name: RiftEssentialsPaper
version: '${project.version}'
main: me.catto.rift.riftessentials.RiftEssentials
api-version: '1.20'
load: STARTUP
authors: [ Catto ]
description: Essential Plugins, Custom Coded For RiftSMP because holy fuck i hate the uselessness of public ones
website: postman2.silverlune.com


# Replace "kit" with the name of your command.
commands:

  minecart:
    description: Grants a player a minecart
    usage: /minecart
    permission: RiftEssentials.give
  boat:
    description: Grants a player a boat
    usage: /boat
    permission: RiftEssentials.give
  nametag:
    description: Grants a player a nametag
    usage: /nametag
    permission: RiftEssentials.give
  ClearBlocks:
    description: Clears blocks in scaffold area
    permission: RiftEssentials.admin
  book:
    description: Grants a player a nametag
    usage: /book
    permission: RiftEssentials.give
  version:
    description: Shows plugin version
    usage: /version
